export const jobs = [
  {
    id: 1,
    company: 'Informatica Labs',
    title: 'Data Scientist',
    location: 'Remote job',
    applicants: 124,
    posted: 'Past 7 days',
    description: 'Drive data modeling and machine learning pipelines to optimize business insights.',
    matchScore: '82%',
    logo: '/assets/images/liner.png',
    level: 'Senior Level',
    stage: 'Series A, B',
    classification: 'Big Tech and Global Tech Giants',
    category: 'Data Science',
  },
  {
    id: 2,
    company: 'Quantify AI',
    title: 'Product Manager',
    location: 'Remote job',
    applicants: 67,
    posted: 'Past 30 days',
    description: 'Lead product development and cross-functional teams to deliver scalable products.',
    matchScore: '78%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Early Stage',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 3,
    company: 'Tesseract Systems',
    title: 'Data Scientist',
    location: 'Remote job',
    applicants: 98,
    posted: 'Past 15 days',
    description: 'Use advanced statistical and ML techniques to generate actionable insights.',
    matchScore: '70%',
    logo: '/assets/images/liner.png',
    level: 'Entry Level',
    stage: 'Series A, B',
    classification: 'Big Tech and Global Tech Giants',
    category: 'Data Science',
  },
  {
    id: 4,
    company: 'Skyloop Technologies',
    title: 'Product Manager',
    location: 'Remote job',
    applicants: 52,
    posted: 'Past 30 days',
    description: 'Own product lifecycle from ideation to go-live in a collaborative environment.',
    matchScore: '81%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Series C+',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 5,
    company: 'NeonByte Corp',
    title: 'Product Manager',
    location: 'Remote job',
    applicants: 69,
    posted: 'Past 15 days',
    description: 'Coordinate market research and user testing to define product strategy.',
    matchScore: '76%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Private',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 6,
    company: 'CredForge',
    title: 'Product Manager',
    location: 'Mumbai',
    applicants: 67,
    posted: 'Past 15 days',
    description: 'Collaborate with engineering and design teams to enhance user experience.',
    matchScore: '83%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Listed',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 7,
    company: 'HyperNova',
    title: 'Product Manager',
    location: 'Mumbai',
    applicants: 61,
    posted: 'Past 7 days',
    description: 'Drive feature roadmap in agile sprints across B2B SaaS products.',
    matchScore: '77%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Early Stage',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 8,
    company: 'AlphaDelta',
    title: 'Product Manager',
    location: 'Mumbai',
    applicants: 59,
    posted: 'Past 30 days',
    description: 'Balance business and technical needs in high-growth product teams.',
    matchScore: '74%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Private',
    classification: 'Growth Stage Startups',
    category: 'Product Management',
  },
  {
    id: 9,
    company: 'InfoAxis Global',
    title: 'Data Scientist',
    location: 'Remote job',
    applicants: 117,
    posted: 'Past 7 days',
    description: 'Develop predictive models and recommendation engines.',
    matchScore: '84%',
    logo: '/assets/images/liner.png',
    level: 'Middle Management',
    stage: 'Series A, B',
    classification: 'Big Tech and Global Tech Giants',
    category: 'Data Science',
  },
  {
    id: 10,
    company: 'Corelytics',
    title: 'Data Scientist',
    location: 'Remote job',
    applicants: 134,
    posted: 'Past 7 days',
    description: 'Work closely with product and analytics teams to deliver impactful solutions.',
    matchScore: '71%',
    logo: '/assets/images/liner.png',
    level: 'Director',
    stage: 'Early Stage',
    classification: 'Big Tech and Global Tech Giants',
    category: 'Data Science',
  },
  {
    id: 11,
    company: 'Verve Insights',
    title: 'Data Scientist',
    location: 'Mumbai',
    applicants: 94,
    posted: 'Past 7 days',
    description: 'Apply ML models on large datasets to solve complex business problems.',
    matchScore: '80%',
    logo: '/assets/images/liner.png',
    level: 'VP',
    stage: 'Series A, B',
    classification: 'Indian Unicorns and Major Startups',
    category: 'Data Science',
  },
  {
    id: 12,
    company: 'ByteBenders',
    title: 'Data Scientist',
    location: 'Remote job',
    applicants: 88,
    posted: 'Past 7 days',
    description: 'Help build data-first infrastructure and real-time analytics engines.',
    matchScore: '73%',
    logo: '/assets/images/liner.png',
    level: 'Junior Management',
    stage: 'Series A, B',
    classification: 'Indian Unicorns and Major Startups',
    category: 'Data Science',
  },
  {
    id: 13,
    company: 'Nexera AI',
    title: 'Data Scientist',
    location: 'Mumbai',
    applicants: 102,
    posted: 'Past 7 days',
    description: 'Collaborate across teams to translate business problems into ML tasks.',
    matchScore: '86%',
    logo: '/assets/images/liner.png',
    level: 'SVP and CXO',
    stage: 'Series A, B',
    classification: 'Indian Unicorns and Major Startups',
    category: 'Data Science',
  },
];
